/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.fare.galileo.shopping.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GalileoTripType implements org.apache.thrift.TEnum {
  OW(0),
  RT(1);

  private final int value;

  private GalileoTripType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GalileoTripType findByValue(int value) { 
    switch (value) {
      case 0:
        return OW;
      case 1:
        return RT;
      default:
        return null;
    }
  }
}
