/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.fare.galileo.shopping.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GalileoCabinType implements org.apache.thrift.TEnum {
  Y(0),
  C(1),
  F(2),
  PY(3),
  PF(4);

  private final int value;

  private GalileoCabinType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GalileoCabinType findByValue(int value) { 
    switch (value) {
      case 0:
        return Y;
      case 1:
        return C;
      case 2:
        return F;
      case 3:
        return PY;
      case 4:
        return PF;
      default:
        return null;
    }
  }
}
