/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.fare.galileo.shopping.requestresponse;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GalileoShoppingResponseStatusEnum implements org.apache.thrift.TEnum {
  Fresh(0),
  Valid(1),
  InValid(2);

  private final int value;

  private GalileoShoppingResponseStatusEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GalileoShoppingResponseStatusEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return Fresh;
      case 1:
        return Valid;
      case 2:
        return InValid;
      default:
        return null;
    }
  }
}
